"""initial schema: orders and transactions

Revision ID: 42a083fc0158
Revises: 
Create Date: 2026-09-15 21:45:09.042050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42a083fc0158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('product', sa.Enum('premium', 'stars', name='producttype'), nullable=False),
    sa.Column('recipient_username', sa.String(length=64), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('stars_amount', sa.Integer(), nullable=True),
    sa.Column('asset', sa.Enum('ton', 'usdt_ton', name='asset'), nullable=False),
    sa.Column('base_price_ton', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('invoice_amount_units', sa.BigInteger(), nullable=True),
    sa.Column('payment_tracker_invoice_id', sa.String(length=128), nullable=True),
    sa.Column('pay_to_address', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'fulfilling', 'fulfilled', 'failed', 'expired', name='orderstatus'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('overpayment', sa.Numeric(precision=20, scale=9), server_default=sa.text('0'), nullable=False),
    sa.Column('paid_by_address', sa.String(length=128), nullable=True),
    sa.Column('fragment_tx_id', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('admin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_tracker_invoice_id')
    )
    op.create_index('ix_orders_status_expires', 'orders', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_orders_telegram_user_id'), 'orders', ['telegram_user_id'], unique=False)
    op.create_index('ix_orders_user_status_created', 'orders', ['telegram_user_id', 'status', 'created_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('asset', sa.Enum('ton', 'usdt_ton', name='asset'), nullable=False),
    sa.Column('overpayment', sa.Numeric(precision=20, scale=9), server_default=sa.text('0'), nullable=False),
    sa.Column('from_address', sa.String(length=128), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index('ix_transactions_order_created', 'transactions', ['order_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_order_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_orders_user_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_telegram_user_id'), table_name='orders')
    op.drop_index('ix_orders_status_expires', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
